### ISSUE TITLE
Upstream to Ruby?

### ISSUE THREAD

**Issue by jdennes** [thekuwayama/caa_rr_patch#2]
I was wondering if you had considered upstreaming this to Ruby?

It seems to me like something that would be a very useful addition to the built in `Resolv::DNS`, and would be great not to have to depend on an additional gem to get the functionality you have added here.

cc: @thekuwayama

**Comment by thekuwayama** [comment]
@jdennes Thank you for your comments!!
It's OK that you can send PR to upstreaming.

**Comment by thekuwayama** [comment]
@jdennes I found this PR that already had been sent.
https://github.com/ruby/ruby/pull/1732
